--卫统
CREATE OR REPLACE VIEW WTIEMBASE AS
select
 iem.iem_mainpage_no
 ,'梅河口市妇幼保健计划生育服务中心' "USERNAME"
 ,"PAYID" "YLFKFS"
 ,"SOCIALCARE" "JKKH"
 ,"INCOUNT" "ZYCS"
 ,"PATNOOFHIS" "BAH"
 ,"NAME" "XM"
 ,"SEXID" "XB"
 ,"BIRTH" "CSRQ"
 ,to_number(replace(regexp_replace(decode(instr(regexp_replace(replace("AGE",'岁',''),'[' || unistr('\0391') || '-' || unistr('\9fa5') || ']','+'),'+'),0,replace("AGE",'岁',''),0),'[^0-9]+','-'),'-',1)) "NL"
 ,"NATIONALITYID" "GJ"
 ,decode(sign(floor(to_number(to_date("ADMITDATE",'yyyy-mm-dd hh24:mi:ss')-to_date("BIRTH",'yyyy-mm-dd hh24:mi:ss'))) - 365),1,0,floor(to_number(to_date("ADMITDATE",'yyyy-mm-dd hh24:mi:ss')-to_date("BIRTH",'yyyy-mm-dd hh24:mi:ss')))) "BZYZSNL"
 ,"WEIGHT" "XSECSTZ"
 ,"INWEIGHT" "XSERYTZ"
 ,"CSD_PROVINCENAME" "CSD"
 ,nvl((SELECT memo FROM areas a   WHERE CATEGORY = 1000 and name like substr("JG_PROVINCENAME",1,2) || '%' and rownum =1),'7') "GG"
 ,"NATIONID" "MZ"
 ,"IDNO" "SFZH"
 ,"JOBID" "ZY"
 ,"MARITAL" "HY"
 ,"XZZ_PROVINCENAME" "XZZ"
 ,"XZZ_TEL" "DH"
 ,"XZZ_POST" "YB1"
 ,"HKDZ_PROVINCENAME" "HKDZ"
 ,"HKDZ_POST" "YB2"
 ,"OFFICEPLACE" "GZDWJDZ"
 ,"OFFICETEL" "DWDH"
 ,"OFFICEPOST" "YB3"
 ,"CONTACTPERSON" "LXRXM"
 ,"RELATIONSHIP" "GX"
 ,"CONTACTADDRESS" "DZ"
 ,"CONTACTTEL" "DH2"
 ,"INHOSTYPE" "RYTJ"
 ,"ADMITDATE" "RYSJ"
 ,"ADMITDATE" "RYSJS"
 ,(select memo from department where id=ADMITDEPT) "RYKB"
 ,"ADMITWARD" "RYBF"
 ,(select memo from department where id=TRANS_ADMITDEPT) "ZKKB"
 ,"OUTWARDDATE" "CYSJ"
 ,"OUTWARDDATE" "CYSJS"
 ,(select memo from department where id=OUTHOSDEPT) "CYKB"
 ,"OUTHOSWARD" "CYBF"
 ,"ACTUALDAYS" "SJZYTS"
 ,"MZXYZD_NAME" "MZZD"
 ,"MZXYZD_CODE" "JBBM"
 ,'' "ZYZD"
 ,'' "JBDM"
 ,'' "RYBQ"


 ,"HURT_TOXICOSIS_ELE_NAME" "WBYY"
 ,"HURT_TOXICOSIS_ELE_ID" "H23"
 ,"PATHOLOGY_DIAGNOSIS_NAME" "BLZD"
 ,"PATHOLOGY_DIAGNOSIS_ID" "JBMM"
 ,"PATHOLOGY_OBSERVATION_SN" "BLH"
 ,"ALLERGIC_FLAG" "YWGM"
 ,"ALLERGIC_DRUG" "GMYW"
 ,"AUTOPSY_FLAG" "SWHZSJ"
 ,"BLOODTYPE" "XX"
 ,decode("RH",'','3',"RH") "RH"
 ,(select name from users s where s.id = SECTION_DIRECTOR) "KZR"
 ,(select name from users s where s.id = DIRECTOR) "ZRYS"
 ,(select name from users s where s.id = VS_EMPLOYEE_CODE) "ZZYS"
 ,(select name from users s where s.id = RESIDENT_EMPLOYEE_CODE) "ZYYS"
 ,(select name from users s where s.id = DUTY_NURSE) "ZRHS"
 ,"REFRESH_EMPLOYEE_CODE" "JXYS"
 ,"INTERNE" "SXYS"
 ,"CODING_USER" "BMY"
 ,"MEDICAL_QUALITY_ID" "BAZL"
 ,"QUALITY_CONTROL_DOCTOR" "ZKYS"
 ,"QUALITY_CONTROL_NURSE" "ZKHS"
 ,"QUALITY_CONTROL_DATE" "ZKRQ"
 ,'' "SSJCZBM1"
 ,'' "SSJCZRQ1"
 ,'' "SSJB1"
 ,'' "SSJCZMC1"
 ,'' "SZ1"
 ,'' "YZ1"
 ,'' "EZ1"
 ,'' "QKDJ1"

 ,'' "MZFS1"
 ,'' "MZYS1"









 ,"OUTHOSTYPE" "LYFS"
 ,"RECEIVEHOSPITAL2" "YZZY_YLJG"
 ,"RECEIVEHOSPITAL2" "WSY_YLJG"
 ,"AGAININHOSPITAL" "SFZZYJH"
 ,"AGAININHOSPITALREASON" "MD"
  ,regexp_replace("BEFOREHOSCOMADAY",'[^0-9]+',0) "RYQ_T"
 ,regexp_replace("BEFOREHOSCOMAHOUR",'[^0-9]+',0)  "RYQ_XS"
 ,regexp_replace("BEFOREHOSCOMAMINUTE",'[^0-9]+',0) "RYQ_F"
 ,regexp_replace("LATERHOSCOMADAY",'[^0-9]+',0) "RYH_T"
 ,regexp_replace("LATERHOSCOMAHOUR",'[^0-9]+',0) "RYH_XS"
 ,regexp_replace("LATERHOSCOMAMINUTE",'[^0-9]+',0) "RYH_F"


 ,0 "ZFY"
 ,0 "ZFJE"
 ,0 "YLFUF"
 ,0 "ZLCZF"
 ,0 "HLF"
 ,0 "QTFY"
 ,0 "BLZDF"
 ,0 "SYSZDF"
 ,0 "YXXZDF"
 ,0 "LCZDXMF"
 ,0 "FSSZLXMF"
 ,0 "WLZLF"
 ,0 "SSZLF"
 ,0 "MAF"
 ,0 "SSF"
 ,0 "KFF"
 ,0 "ZYZLF"
 ,0 "XYF"
 ,0 "KJYWF"
 ,0 "ZCYF"
 ,0 "ZCYF1"
 ,0 "XF"
 ,0 "BDBLZPF"
 ,0 "QDBLZPF"
 ,0 "NXYZLZPF"
 ,0 "XBYZLZPF"
 ,0 "HCYYCLF"
 ,0 "YYCLF"
 ,0 "YCXYYCLF"
 ,0 "QTF"


/* ,(select PRACTICECODE from users s where s.id = SECTION_DIRECTOR) "B22C"

 ,(select PRACTICECODE from users s where s.id = DIRECTOR) "B23C"

 ,(select PRACTICECODE from users s where s.id = VS_EMPLOYEE_CODE) "B24C"

 ,(select PRACTICECODE from users s where s.id = RESIDENT_EMPLOYEE_CODE) "B25C"

 ,(select PRACTICECODE from users s where s.id = DUTY_NURSE) "B26C"*/


from IEM_MAINPAGE_BASICINFO_SX iem where iem.valide =1;



--上报

CREATE OR REPLACE VIEW IEMBASE AS
select
 iem.iem_mainpage_no
 ,'12220581412979059X' "A01"
 ,'梅河口市妇幼保健计划生育服务中心' "A02"
 ,"PATNOOFHIS" "A48"
 ,"INCOUNT" "A49"
 ,"ADMITDATE" "B12"
 ,"OUTWARDDATE" "B15"
 ,"SOCIALCARE" "A47"
 ,"PAYID" "A46C"
 ,"NAME" "A11"
 ,"SEXID" "A12C"
 ,"BIRTH" "A13"
 ,to_number(replace(regexp_replace(decode(instr(regexp_replace(replace("AGE",'岁',''),'[' || unistr('\0391') || '-' || unistr('\9fa5') || ']','+'),'+'),0,replace("AGE",'岁',''),0),'[^0-9]+','-'),'-',1)) "A14"
 ,"NATIONALITYID" "A15C"
 ,"MARITAL" "A21C"
 ,"JOBID" "A38C"
 ,"NATIONID" "A19C"
 ,'1' "A20N"
 ,"IDNO" "A20"
 ,"CSD_PROVINCENAME" "A22"
 ,nvl((SELECT memo FROM areas a   WHERE CATEGORY = 1000 and name like substr("JG_PROVINCENAME",1,2) || '%' and rownum =1),'7') "A23C"
-- ,'7' "A23C"
 ,"HKDZ_PROVINCENAME" "A24"
 ,"HKDZ_POST" "A25C"
 ,"XZZ_PROVINCENAME" "A26"
 ,"XZZ_TEL" "A27"
 ,"XZZ_POST" "A28C"
 ,"OFFICEPLACE" "A29"
 ,"OFFICETEL" "A30"
 ,"OFFICEPOST" "A31C"
 ,"CONTACTPERSON" "A32"
 ,"RELATIONSHIP" "A33C"
 ,"CONTACTADDRESS" "A34"
 ,"CONTACTTEL" "A35"
 ,'0' "B38"
 ,"INHOSTYPE" "B11C"
 ,(select memo from department where id=ADMITDEPT) "B13C"
 ,"ADMITWARD" "B14"
 ,(select memo from department where id=TRANS_ADMITDEPT) "B21C"
 ,(select memo from department where id=OUTHOSDEPT) "B16C"
 ,"OUTHOSWARD" "B17"
 ,"ACTUALDAYS" "B20"
 ,"MZXYZD_CODE" "C01C"
 ,"MZXYZD_NAME" "C02N"
 ,decode("INHOSINFO",'4','2','','3',"INHOSINFO") "F01"
 ,"RYXYZD_CODE" "F02C"
 ,"RYXYZD_NAME" "F03N"
 ,"MAINDIAGDATE" "F04"

 ,'' "C03C"
 ,'' "C04N"
 ,'' "C05C"
 ,'' "F05"



 ,"PATHOLOGY_DIAGNOSIS_ID" "C09C"
 ,"PATHOLOGY_DIAGNOSIS_NAME" "C10N"
 ,"PATHOLOGY_OBSERVATION_SN" "C11"
 ,'' "F07x01C"
 ,'' "F08x01N"
 ,'' "F09x01"
 ,'' "F07x02C"
 ,'' "F08x02N"
 ,'' "F09x02"
 ,"HURT_TOXICOSIS_ELE_ID" "C12C"
 ,"HURT_TOXICOSIS_ELE_NAME" "C13N"
 ,"ALLERGIC_FLAG" "C24C"
 ,"ALLERGIC_DRUG" "C25"
 ,'' "F10"
 ,'' "F11"
 ,'' "F12"
 ,(select PRACTICECODE from users s where s.id = SECTION_DIRECTOR) "B22C"
 ,(select name from users s where s.id = SECTION_DIRECTOR) "B22"
 ,(select PRACTICECODE from users s where s.id = DIRECTOR) "B23C"
 ,(select name from users s where s.id = DIRECTOR) "B23"
 ,(select PRACTICECODE from users s where s.id = VS_EMPLOYEE_CODE) "B24C"
 ,(select name from users s where s.id = VS_EMPLOYEE_CODE) "B24"
 ,(select PRACTICECODE from users s where s.id = RESIDENT_EMPLOYEE_CODE) "B25C"
 ,(select name from users s where s.id = RESIDENT_EMPLOYEE_CODE) "B25"
 ,(select PRACTICECODE from users s where s.id = DUTY_NURSE) "B26C"
 ,(select name from users s where s.id = DUTY_NURSE) "B26"
 ,"REFRESH_EMPLOYEE_CODE" "B27"
 ,"INTERNE" "B28"
 ,"CODING_USER" "B29"
 ,"MEDICAL_QUALITY_ID" "B30C"
 ,"QUALITY_CONTROL_DOCTOR" "B31"
 ,"QUALITY_CONTROL_NURSE" "B32"
 ,"QUALITY_CONTROL_DATE" "B33"
 ,"AUTOPSY_FLAG" "C34C"
 ,"BLOODTYPE" "C26C"
 ,decode("RH",'','3',"RH") "C27C"
 ,'' "C14x01C"
 ,'' "C15x01N"
 ,'' "C16x01"
 ,'' "C17x01"
 ,0 "F13"
 ,'' "C18x01"
 ,'' "C19x01"
 ,'' "C20x01"
 ,'' "C21x01C"
 ,'' "C22x01C"
 ,'' "F15"
 ,'' "C23x01"



 ,0 "F17"
 ,0 "F18"
 ,0 "F19"
 ,0 "F20"
 ,0 "F21"
 ,0 "F22"
 ,0 "F23"
 ,0 "F24"
 ,0 "F25"
 ,0 "F26"
 ,decode(sign(floor(to_number(to_date("ADMITDATE",'yyyy-mm-dd hh24:mi:ss')-to_date("BIRTH",'yyyy-mm-dd hh24:mi:ss'))) - 365),1,0,floor(to_number(to_date("ADMITDATE",'yyyy-mm-dd hh24:mi:ss')-to_date("BIRTH",'yyyy-mm-dd hh24:mi:ss')))) "A16"
 ,"WEIGHT" "A18x01"
 ,"WEIGHT" "A18x02"
 ,"WEIGHT" "A18x03"
 ,"WEIGHT" "A18x04"
 ,"WEIGHT" "A18x05"
 ,"INWEIGHT" "A17"
 ,regexp_replace("BEFOREHOSCOMADAY",'[^0-9]+',0) "C28"
 ,regexp_replace("BEFOREHOSCOMAHOUR",'[^0-9]+',0)  "C29"
 ,regexp_replace("BEFOREHOSCOMAMINUTE",'[^0-9]+',0) "C30"
 ,regexp_replace("LATERHOSCOMADAY",'[^0-9]+',0) "C31"
 ,regexp_replace("LATERHOSCOMAHOUR",'[^0-9]+',0) "C32"
 ,regexp_replace("LATERHOSCOMAMINUTE",'[^0-9]+',0) "C33"
 ,0 "C47"
 ,'' "C48x01C"
 ,'' "C49x01"
 ,'' "C50x01"
 ,'' "C48x02C"
 ,'' "C49x02"
 ,'' "C50x02"
 ,'' "C48x03C"
 ,'' "C49x03"
 ,'' "C50x03"
 ,'' "C48x04C"
 ,'' "C49x04"
 ,'' "C50x04"
 ,'' "C48x05C"
 ,'' "C49x05"
 ,'' "C50x05"
 ,"AGAININHOSPITAL" "B36C"
 ,"AGAININHOSPITALREASON" "B37"
 ,"OUTHOSTYPE" "B34C"
 ,"RECEIVEHOSPITAL2" "B35"
 ,0 "D01"
 ,0 "D09"
 ,0 "D11"
 ,0 "D12"
 ,0 "D13"
 ,0 "D14"
 ,0 "D15"
 ,0 "D16"
 ,0 "D17"
 ,0 "D18"
 ,0 "D19"
 ,0 "D19x01"
 ,0 "D20"
 ,0 "D20x01"
 ,0 "D20x02"
 ,0 "D21"
 ,0 "D22"
 ,0 "D23"
 ,0 "D23x01"
 ,0 "D24"
 ,0 "D25"
 ,0 "D26"
 ,0 "D27"
 ,0 "D28"
 ,0 "D29"
 ,0 "D30"
 ,0 "D31"
 ,0 "D32"
 ,0 "D33"
 ,0 "D34"

from IEM_MAINPAGE_BASICINFO_SX iem where iem.valide =1;

