//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrectSoft.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrectSoft.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 属性不能设置为空 的本地化字符串。
        /// </summary>
        internal static string CannotSetNullValue {
            get {
                return ResourceManager.GetString("CannotSetNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类未实现 的本地化字符串。
        /// </summary>
        internal static string ClassNotImplement {
            get {
                return ResourceManager.GetString("ClassNotImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 文件未找到 的本地化字符串。
        /// </summary>
        internal static string CommonFileNotFind {
            get {
                return ResourceManager.GetString("CommonFileNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 为空 的本地化字符串。
        /// </summary>
        internal static string CommonParameterIsNull {
            get {
                return ResourceManager.GetString("CommonParameterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不能小于{0} 的本地化字符串。
        /// </summary>
        internal static string CommonValueIsLess {
            get {
                return ResourceManager.GetString("CommonValueIsLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举标志不存在 的本地化字符串。
        /// </summary>
        internal static string EnumFlagNofExist {
            get {
                return ResourceManager.GetString("EnumFlagNofExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不正确 的本地化字符串。
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不正确 的本地化字符串。
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只读对象 的本地化字符串。
        /// </summary>
        internal static string ObjectIsReadOnly {
            get {
                return ResourceManager.GetString("ObjectIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停长期医嘱 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_CeaseLong {
            get {
                return ResourceManager.GetString("OrderContentKind_CeaseLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费项目医嘱 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_ChargeItem {
            get {
                return ResourceManager.GetString("OrderContentKind_ChargeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临床项目医嘱 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_ClinicItem {
            get {
                return ResourceManager.GetString("OrderContentKind_ClinicItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 药品医嘱 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_Druggery {
            get {
                return ResourceManager.GetString("OrderContentKind_Druggery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规医嘱 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_GeneralItem {
            get {
                return ResourceManager.GetString("OrderContentKind_GeneralItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_None {
            get {
                return ResourceManager.GetString("OrderContentKind_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手术医嘱 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_Operation {
            get {
                return ResourceManager.GetString("OrderContentKind_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出院带药 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_OutDruggery {
            get {
                return ResourceManager.GetString("OrderContentKind_OutDruggery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纯医嘱(术后) 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_TextAfterOperation {
            get {
                return ResourceManager.GetString("OrderContentKind_TextAfterOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纯医嘱(出院) 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_TextLeaveHospital {
            get {
                return ResourceManager.GetString("OrderContentKind_TextLeaveHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纯医嘱(普通) 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_TextNormal {
            get {
                return ResourceManager.GetString("OrderContentKind_TextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纯医嘱(转科) 的本地化字符串。
        /// </summary>
        internal static string OrderContentKind_TextShiftDept {
            get {
                return ResourceManager.GetString("OrderContentKind_TextShiftDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--Sample XML file generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)--&gt;
        ///&lt;PreDefineSqlCollection xmlns=&quot;http://www.DrectSoft.com.cn/orm&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.DrectSoft.com.cn/orm  PreDefSqlSentence.xsd&quot;&gt;
        ///  &lt;SelectSentence Name=&quot;SelectDepartment&quot;&gt;
        ///    &lt;QuerySentence&gt;select ID DeptID,Name DeptName,Py,Wb,HosNo,Sort DeptCatalog,Mark DeptMark,TotalChief,TotalResident,TotalAttend,TotalNurse,TotalBed [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PreDefSqlSentence {
            get {
                return ResourceManager.GetString("PreDefSqlSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息为空 的本地化字符串。
        /// </summary>
        internal static string UserInfoIsNull {
            get {
                return ResourceManager.GetString("UserInfoIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Wordbooks xmlns=&quot;http://www.DrectSoft.com.cn/Wordbook&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.DrectSoft.com.cn/Wordbook
        ///DrectSoftWordbooks.xsd&quot;&gt;
        ///	&lt;WordbookCatalog CatalogName=&quot;Hospital&quot; Caption=&quot;医院基本设置&quot;&gt;
        ///	&lt;Wordbook WordbookName=&quot;GeneralSqlBook&quot; Caption=&quot;体检预约项目&quot;&gt;
        ///			&lt;QuerySentence&gt;SelectYYXMK&lt;/QuerySentence&gt;
        ///			&lt;CodeField&gt;tj_dxm_id&lt;/CodeField&gt;
        ///			&lt;NameField&gt;name&lt;/NameField&gt;
        ///			&lt;CodeFieldIsString&gt;true&lt;/CodeFieldIsStr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DrectSoftWordbooks {
            get {
                return ResourceManager.GetString("DrectSoftWordbooks", resourceCulture);
            }
        }
    }
}
